[package]
name = "RustRaft"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
tokio = { version = "1.47.1", features = ["full"] }
chrono = { version = "0.4", features = ["clock"] }
#clippy = "0.0.302"
